services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentsis-api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://admin:P@ssw0rd@db:5432/dentsis
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
